---
openapi: 3.0.0
info:
  title: Vonage Meetings Public API
  version: 0.1.0
servers:
- url: /api
paths:
  /rooms:
    get:
      summary: Get all available rooms
      operationId: getRooms
      parameters:
        - $ref: "#/components/parameters/start_id_parameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                properties:
                  page_size:
                    type: integer
                    example: 10
                    description: The number of results returned on this page.
                  _embedded:
                    type: object
                    properties:
                      rooms:
                        type: array
                        description: List of all accessible rooms 
                        items:
                          $ref: "#/components/schemas/Room"
                  _links:
                    type: object
                    properties:
                      first:
                        type: object
                        properties:
                          href:
                            type: string
                            example: "https://api.nexmo.com/v0.1/meetings/rooms?page_size=10"
                      self:
                        type: object
                        properties:
                          href:
                            type: string
                            example: "https://api.nexmo.com/v0.1/meetings/rooms?page_size=10&start_id=20"
                      next:
                        type: object
                        properties:
                          href:
                            type: string
                            example: "https://api.nexmo.com/v0.1/meetings/rooms?page_size=10&start_id=30"
                      prev:
                        type: object
                        properties:
                          href:
                            type: string
                            example: "https://api.nexmo.com/v0.1/meetings/rooms?page_size=10&end_id=20"

    post:
      summary: Create a room
      operationId: createRoom
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoomDetails'
        required: true
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        "400":
          description: Bad Request
  /rooms/:room_id:
    get:
      summary: Get room details
      operationId: getRoom
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        "404":
          description: Room not found
    delete:
      summary: Delete a room
      operationId: deleteRoom
      responses:
        "204":
          description: OK
        "404":
          description: Room not found
  /recordings/:recording_id:
    get:
      summary: Get a recording
      operationId: getRecording
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recording'
        "404":
          description: Recording not found
    delete:
      summary: Delete a recording
      operationId: deleteRecording
      responses:
        "204":
          description: No Content
        "403":
          description: Can only delete recordings in 'uploaded' status
        "404":
          description: Recording not found
  /sessions/:session_id/recordings:
    get:
      summary: Get recordings of a session
      operationId: getSessionRecordings
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _embedded:
                    type: object
                    properties:
                      recordings:
                        type: array
                        description: List of recordings for the given session
                        items:
                          $ref: "#/components/schemas/Recording"
        "404":
          description: Session not found
  /dial-in-numbers:
    get:
      summary: Get numbers that can be used to dial into a meeting
      operationId: getDialInNumbers
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DialInNumber'
components:
  parameters:
    start_id_parameter:
      name: start_id
      in: query
      schema:
        type: string
      example: 13
      required: false
      description: The ID to start returning events at
    end_id_parameter:
      name: end_id
      in: query
      schema:
        type: string
      example: 13
      required: false
      description: The ID to end returning events at (excluding end_id itself)
  schemas:
    Room:
      type: object
      properties:
        id:
          type: string
          format: uuid
        display_name:
          type: string
          maxLength: 200
        pin_code:
          minLength: 9
          pattern: ^\d+$
          type: string
          example: "123456789"
        _links:
          type: object
          properties:
            guest_url:
              type: string
              format: uri
              example: "https://meetings.vonage.com/123456789"
            host_url:
              type: string
              format: uri
              example: "https://meetings.vonage.com/123456789?participant_token=xyz"
    CreateRoomDetails:
      type: object
      properties:
        display_name:
          maxLength: 200
          type: string
    Recording:
      type: object
      properties:
        id:
          type: string
          format: uuid
        session_id:
          type: string
          format: uuid
        started_at:
          type: string
          format: date-time
        ended_at:
          type: string
          format: date-time
        status:
          type: string
          enum:
          - started
          - stopped
          - paused
          - uploaded
        _links:
          type: object
          properties:
            url:
              type: string
              format: uri
    DialInNumber:
      type: object
      properties:
        number:
          type: string
          example: "17323338801"
        locale:
          type: string
          example: "en-US"
        display_name:
          type: string
          example: "United States"
